project_id = "flwcasyydljhrjlrtzlz"

[functions.quickbooks-callback]
verify_jwt = true

[functions.quickbooks-auth]
verify_jwt = true

[functions.quickbooks-validate-credentials]
verify_jwt = true

[functions.quickbooks-check-auth]
verify_jwt = true

[functions.quickbooks-sync-all]
verify_jwt = true

[functions.quickbooks-refresh-token]
verify_jwt = true

[functions.quickbooks-sync-balance]
verify_jwt = true

[functions.quickbooks-sync-profit-loss]
verify_jwt = true

[functions.quickbooks-sync-budgets]
verify_jwt = true

[functions.quickbooks-balance]
verify_jwt = true

[functions.quickbooks-income]
verify_jwt = true

[functions.quickbooks-accounts-receivable]
verify_jwt = true

[functions.quickbooks-accounts-payable]
verify_jwt = true

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false
