project_id = "flwcasyydljhrjlrtzlz"

[functions.qb-auth]
verify_jwt = true

[functions.qb-sync]
verify_jwt = true

[functions.quickbooks-callback]
verify_jwt = true

[functions.quickbooks-auth]
verify_jwt = true

[functions.quickbooks-validate-credentials]
verify_jwt = true

[functions.quickbooks-check-auth]
verify_jwt = true